### ISSUE TITLE
Add a timer to hexmap_allocation

### ISSUE THREAD

**Issue by dicook** [srkobakian/sugarbag#1]

**Comment by srkobakian** [comment]
Using system.time for our testing and development use? or have a timer/progress bar that is user facing?

**Comment by dicook** [comment]
Need to have something to indicate how much longer to wait for the allocation. A progress bar would be good.  Right now it is printing out every allocation, which is nice for debugging, but the user just needs to know how many more to do.

**Comment by srkobakian** [comment]
Good point, I know Earo has implemented progress bars, I will have a look at her github.
Do you have any other examples I should explore?

**Comment by srkobakian** [comment]
Progress bar implemented, may need to indicate it won't be a linear time progression.
As distance considered from centroid expands, the time taken is longer. 
May need to consider a check for this, eg if the grid filtering returns over a certain amount of possible points, reset the filtering distance to a smaller value to speed up algorithm for sparse rural areas.
