### ISSUE TITLE
Adapt to dev tidyr, slated to become v1.0.0

### ISSUE THREAD

**Issue by jennybc** [srkobakian/sugarbag#11]
Can you take a look at these problems we see in revdep check for tidyr? The release of v1.0.0 is on the horizon. Looks like something related to name repair.

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#sugarbag

**Comment by srkobakian** [comment]
Thank you for bringing this to our attention, we will update sugarbag for the dev version of tidyr.

**Comment by srkobakian** [comment]
Issues solved by new unnest strategy
