### ISSUE TITLE
Remove hard coded variables in centroids or add documentation on structure

### ISSUE THREAD

**Issue by emitanaka** [srkobakian/sugarbag#12]
E.g. for `create_grids`, it wasn't obvious to me that the centroids argument required a data frame with variables explicitly named `longitude` and `latitude`. A flexibility to refer to any columns for lat and lon is desirable IMO. That way I don't need an intermediate step to create a data frame with latitude and longitude. 

(happy to do pull request on this if you like)

**Comment by srkobakian** [comment]
That would be fantastic Emi!

**Comment by srkobakian** [comment]
Possible solution: 
Function arguments for the names of columns, with defaults of longitude and latitude and an error thrown if no reasonable approximation is found in the column names of the data eg lon and lat?
