### ISSUE TITLE
Replace deprecated functions

### ISSUE THREAD

**Issue by emitanaka** [srkobakian/sugarbag#13]
E.g. the use of `as.tibble` gives warning messages that it is deprecated.

**Comment by srkobakian** [comment]
Is there an automated way to check for use of deprecated functions?

**Comment by mitchelloharawild** [comment]
Deprecated function usage should show up as warnings in the package checks.

**Comment by srkobakian** [comment]
Thank you @mitchelloharawild I will have a look at that

**Comment by srkobakian** [comment]
The deprecated functions should now be replaced.
