### ISSUE TITLE
Be explicit if variable is a data or env variable in dplyr verbs

### ISSUE THREAD

**Issue by emitanaka** [srkobakian/sugarbag#14]
My centroids data had an `x` variable. This caused an issue downstream where `lat_window` was calculated as it was using the `x` in the centroids data instead of x in the environment (e.g. below with `.env$x[1]`).

```
lat_window <- function(x, cents = centroids, maximum = nlat) {
    max_int <- min(x[2], maximum)

    cents_in <- filter(cents, between(lat_int, .env$x[1], max_int))
    return(cents_in)
  }
```

**Comment by emitanaka** [comment]
The error downstream:
``` r
library(eechidna)
library(tidyverse)
library(sugarbag)
nat_data19 <- nat_data_download(2019)
#> 
#> Attaching package: 'sugarbag'
#> The following object is masked from 'package:eechidna':
#> 
#>     fp19
nat_data19 %>% 
  mutate(longitude = long_c, latitude = lat_c) %>% 
  create_grid(hex_size = 0.9, buffer_dist = 5)
#> Source: local data frame [0 x 12]
#> Groups: <by row>
#> 
#> # A tibble: 0 x 12
#> # … with 12 variables: hex_long <dbl>, hex_lat <dbl>, id <int>,
#> #   assigned <lgl>, hex_long_int <dbl>, hex_lat_int <dbl>,
#> #   mean_long_min <dbl>, mean_long_max <dbl>, mean_lat_min <dbl>,
#> #   mean_lat_max <dbl>, long_buffer <lgl>, lat_buffer <lgl>
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sa-lee** [comment]
Would the easiest solution here be to not use  non-standard eval at all? The example function doesn’t really need it.

**Comment by emitanaka** [comment]
I'd say use `dplyr` verbs if it's going to be a dependent package. I do think `dplyr` syntax is a lot easier to read but just maybe more work for the developer to watch out for tidy evaluations and keeping up with the evolving `dplyr`.
