### ISSUE TITLE
readme typo?

### ISSUE THREAD

**Issue by emitanaka** [srkobakian/sugarbag#15]
There seems to be two LNP in the readme:
```
auscolours <- c(
  "ALP" = "#DE3533",
  "LNP" = "#080CAB",
  "KAP" = "#b50204",
  "GRN" = "#10C25B",
  "XEN" = "#ff6300",
  "LNP" = "#0047AB",
  "IND" = "#307560")
```

**Comment by srkobakian** [comment]
Definitely a typo. I have been trying to rewrite the READMe example.
It would be fantastic to workshop a good example with you.

**Comment by emitanaka** [comment]
Would be happy to @srkobakian :)
