### ISSUE TITLE
Add option for exporting hexagons as an sf data set

### ISSUE THREAD

**Issue by srkobakian** [srkobakian/sugarbag#19]
Potential issues: may also require projection to be provided

**Comment by ran-codes** [comment]
great package! I would love to export the hexagons as sf object.

has this sf export feature been implemented? I can't find it in the documentation.

**Comment by dicook** [comment]
Hi Ran, This seems do-able! 

> On 15 Nov 2022, at 6:28 am, Ran Li ***@***.***> wrote:
> 
> 
> great package! I would love to export the hexagons as sf object.
> 
> has this sf export feature been implemented? I can't find it in the documentation.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.
> 

cheers,
Di

---
Dianne Cook
***@***.***
