### ISSUE TITLE
break in while loop needed

### ISSUE THREAD

**Issue by dicook** [srkobakian/sugarbag#2]
while(NROW(f_grid) == 0) {
        f_grid <- filter_grid_points(f_grid = hex_grid, f_centroid = centroid, f_dist = filter_dist)
        if (NROW(f_grid) == 0) {
        filter_dist <- filter_dist*1.5
        print(paste("Filter Distance expanded 50% to ", filter_dist))
        }
    }

The endless loop occurs because there are no more available points in the direction, with the current buffer. You should be able to work out a maximum expansion size possible, based on the largest inter-grid point distance. When you reach this, break out of the while loop, print a warning to the user, and allocate to a randomly available grid point. 

Expanding the buffer fixes the endless loop, temporarily.

"while"'s always need an escape route

**Comment by srkobakian** [comment]
Working on it now.

**Comment by srkobakian** [comment]
While loop now breaks when limit is reached. 
Expanded distance is applied to all future hexagons considered. 
Expansion of distance considered is now linear, helps with speed.
