### ISSUE TITLE
Translation between sf and tibble

### ISSUE THREAD

**Issue by dicook** [srkobakian/sugarbag#4]
We need to be able to translate the polygon data from sf to tibble and back again. I recommend making a function to do this.

**Comment by srkobakian** [comment]
Function created. When not applied to Australia we will need to allow people to specify projections in read_shp and sfc_to_tibble functions. Currently hard-coding projection.

**Comment by dicook** [comment]
- [x] function to extract data into Tibbles, containing the hex centres
- [x] add option to add data, as repeated measures to the polygon Tibbles, this should be the default
- [x] create 7 points per hexagon data set to experiment with drawing using geom_polygon

**Comment by dicook** [comment]
underlay maps to any display

**Comment by dicook** [comment]
try animation between hex and map, using a small data set, eg Melbourne or Hobart

Look for: 
- [ ] Transition of nested SA2 areas
- [ ] Speed of morph with different amounts of polygon points
- [ ] Areas switching (crossing over each other) when animating between geographic and hexagon locations

**Comment by srkobakian** [comment]
We can create two sets of data: fortified geographic polygons and 7 point hexagon polygons.

- [ ] Transition between them as is
- [ ] Read gganimate literature 
- [ ] Match polygon points to a specific hexagon point 
- [ ] Transition between joined data sets

**Comment by srkobakian** [comment]
Can easily plot geom_poly of hex and geo on same ggplot
