### ISSUE TITLE
geofacet

### ISSUE THREAD

**Issue by dicook** [srkobakian/sugarbag#5]
We want to be able to facet small chunks of the map, but the position in the facet should roughly match the geographic location. Like the geofacet package, but it only has US state layout currently. We would need to do a rough layout.

**Comment by srkobakian** [comment]
Rough layout at SA4 level implemented as table in data, facet_grid replaced with facet_geo.
17 plots, very different scales, need to discuss free scales and associated issues.

**Comment by dicook** [comment]
play with text size, panel? size to maximise plot space

**Comment by dicook** [comment]
get sa4 spatial data to be able to extract centroids

**Comment by srkobakian** [comment]
Changed the panel labeling to smaller names, removed axis text, removed one row
